name: CommandAlias
version: 1.6.7-RELEASE
author: PotatoTheEllie
description: Easy, Lightweight plugin for easy command aliases.
website: www.elliepotato.de/support

softdepend: [ PlaceholderAPI ]

main: de.elliepotato.commandalias.CommandAlias
api-version: 1.13

commands:
  ca:
    description: CommandAlias in-game manager